import { create } from "zustand";
import {InventoryI} from "@/storage/interface/inventory";


export const useInventoryStore = create<InventoryI>((set) => ({
    items: [
        {
            appId: 730,
            gunName: "AK-47",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhoyszedDNH-NOJhJWZh_vxDLbUkmJE5fp9i_vG8MLx2Qbl-xVpYDvzLISde1c_YQ6Dr1m-we7ohpG46MjMn3Y2vnZ04HyOgVXp1mer_etC",
            isSouvenir: false,
            isStatTrack: true,
            isTradable: true,
            marketHashName: "AK-47 | Baroque Purple (Field-Tested)",
            price: 467.32,
            rarity: "Industrial",
            skinName: "Baroque Purple",
            wear: "Minimal Wear",
            id: "1",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "AK-47",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJegJM6dO4q5KCk_LmDLbUkmJE5fp9i_vG8MKljgDjrkpuZmGiIISRIFU_aQrV81a9kObojMPt6JSYnCRl63Zx5CzZgVXp1oPn8d3r",
            isSouvenir: true,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "AK-47 | Bloodsport (Minimal Wear)",
            price: 2016.68,
            rarity: "Covert",
            skinName: "Bloodsport",
            wear: "Minimal Wear",
            id: "2",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "M4A1-S",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou-6kejhz2v_Nfz5H_uO1gb-Gw_alIITCmX5d_MR6j_v--YXygECLpxIuNDztII-We1I4aAqE_Fi_lerthMXttc7OnXRmvyhw4Xndlx3kiUkfa-ZuguveFwseJK64Qw",
            isSouvenir: false,
            isStatTrack: true,
            isTradable: true,
            marketHashName: "M4A1-S | Chantico's Fire (Factory New)",
            price: 3520.47,
            rarity: "Covert",
            skinName: "Chantico's Fire",
            wear: "Factory New",
            id: "3",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "Desert Eagle",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposr-kLAtl7PvRTipH7s-JkIGZnPLmDLbUkmJE5fp9i_vG8ML22wbj-0tqZG_2INeTdgc-Zl_S-FbqxL-71J60up7IzSY36CkmsXnUgVXp1lzsUQgy",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "Desert Eagle | Crimson Web (Field-Tested)",
            price: 127.50,
            rarity: "Classified",
            skinName: "Crimson Web",
            wear: "Field-Tested",
            id: "4",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "P250",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopujwezhjxszYI2gS09G3moSKm_bLP7LWnn9u5MRjjeyPpY32igHl_0VoMD30JoCRcVU4MFmGrwfvl-bohpC-tJWcm3c3uiJ04mGdwUJxLpw2dQ",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "P250 | Muertos (Minimal Wear)",
            price: 210.34,
            rarity: "Classified",
            skinName: "Muertos",
            wear: "Minimal Wear",
            id: "5",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "MAG-7",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou7uifDhoyszBcjJR7dSzkJKEmcj4OrzZglRd6dd2j6fHoon00Fe3qkM-Z2GiJIKTcVI-aV_Xqwe3kufr0JHquZmdySRi7icr-z-DyKuim8q8",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "MAG-7 | Memento (Minimal Wear)",
            price: 34.80,
            rarity: "Classified",
            skinName: "Classified",
            wear: "Minimal Wear",
            id: "6",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "XM1014",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgporrf0e1Y07PDdTiVPvYznwL-IluX9J7rCqWdY781lteXA54vwxgTi-xZqYG77coPHd1dsZw6D_1Lvw7q9gZO96p6dz3oxsiAh5inenxGpwUYbnX3d0Ig",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "XM1014 | Tranquility (Factory New)",
            price: 465.00,
            rarity: "Industrial",
            skinName: "Tranquility",
            wear: "Factory New",
            id: "7",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "AK-47",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJegJM6dO4q5KCk_LmDLbUkmJE5fp9i_vG8MKljgDjrkpuZmGiIISRIFU_aQrV81a9kObojMPt6JSYnCRl63Zx5CzZgVXp1oPn8d3r",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "AK-47 | Bloodsport (Minimal Wear)",
            price: 2016.68,
            rarity: "Covert",
            skinName: "Bloodsport",
            wear: "Minimal Wear",
            id: "8",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "M4A1-S",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou-6kejhz2v_Nfz5H_uO1gb-Gw_alIITCmX5d_MR6j_v--YXygECLpxIuNDztII-We1I4aAqE_Fi_lerthMXttc7OnXRmvyhw4Xndlx3kiUkfa-ZuguveFwseJK64Qw",
            isSouvenir: false,
            isStatTrack: true,
            isTradable: true,
            marketHashName: "M4A1-S | Chantico's Fire (Factory New)",
            price: 3520.47,
            rarity: "Covert",
            skinName: "Chantico's Fire",
            wear: "Factory New",
            id: "9",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "AK-47",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJegJM6dO4q5KCk_LmDLbUkmJE5fp9i_vG8MKljgDjrkpuZmGiIISRIFU_aQrV81a9kObojMPt6JSYnCRl63Zx5CzZgVXp1oPn8d3r",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "AK-47 | Bloodsport (Minimal Wear)",
            price: 2016.68,
            rarity: "Covert",
            skinName: "Bloodsport",
            wear: "Minimal Wear",
            id: "10",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "AK-47",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhoyszedDNH-NOJhJWZh_vxDLbUkmJE5fp9i_vG8MLx2Qbl-xVpYDvzLISde1c_YQ6Dr1m-we7ohpG46MjMn3Y2vnZ04HyOgVXp1mer_etC",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "AK-47 | Baroque Purple (Field-Tested)",
            price: 467.32,
            rarity: "Industrial",
            skinName: "Baroque Purple",
            wear: "Field-Tested",
            id: "11",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "AK-47",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJegJM6dO4q5KCk_LmDLbUkmJE5fp9i_vG8MKljgDjrkpuZmGiIISRIFU_aQrV81a9kObojMPt6JSYnCRl63Zx5CzZgVXp1oPn8d3r",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "AK-47 | Bloodsport (Minimal Wear)",
            price: 2016.68,
            rarity: "Covert",
            skinName: "Bloodsport",
            wear: "Minimal Wear",
            id: "12",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "M4A1-S",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou-6kejhz2v_Nfz5H_uO1gb-Gw_alIITCmX5d_MR6j_v--YXygECLpxIuNDztII-We1I4aAqE_Fi_lerthMXttc7OnXRmvyhw4Xndlx3kiUkfa-ZuguveFwseJK64Qw",
            isSouvenir: false,
            isStatTrack: true,
            isTradable: true,
            marketHashName: "M4A1-S | Chantico's Fire (Factory New)",
            price: 3520.47,
            rarity: "Covert",
            skinName: "Chantico's Fire",
            wear: "Factory New",
            id: "13",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "Desert Eagle",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgposr-kLAtl7PvRTipH7s-JkIGZnPLmDLbUkmJE5fp9i_vG8ML22wbj-0tqZG_2INeTdgc-Zl_S-FbqxL-71J60up7IzSY36CkmsXnUgVXp1lzsUQgy",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "Desert Eagle | Crimson Web (Field-Tested)",
            price: 127.50,
            rarity: "Classified",
            skinName: "Crimson Web",
            wear: "Field-Tested",
            id: "14",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "P250",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpopujwezhjxszYI2gS09G3moSKm_bLP7LWnn9u5MRjjeyPpY32igHl_0VoMD30JoCRcVU4MFmGrwfvl-bohpC-tJWcm3c3uiJ04mGdwUJxLpw2dQ",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "P250 | Muertos (Minimal Wear)",
            price: 210.34,
            rarity: "Classified",
            skinName: "Muertos",
            wear: "Minimal Wear",
            id: "15",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "MAG-7",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou7uifDhoyszBcjJR7dSzkJKEmcj4OrzZglRd6dd2j6fHoon00Fe3qkM-Z2GiJIKTcVI-aV_Xqwe3kufr0JHquZmdySRi7icr-z-DyKuim8q8",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "MAG-7 | Memento (Minimal Wear)",
            price: 34.80,
            rarity: "Classified",
            skinName: "Classified",
            wear: "Minimal Wear",
            id: "16",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "XM1014",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgporrf0e1Y07PDdTiVPvYznwL-IluX9J7rCqWdY781lteXA54vwxgTi-xZqYG77coPHd1dsZw6D_1Lvw7q9gZO96p6dz3oxsiAh5inenxGpwUYbnX3d0Ig",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "XM1014 | Tranquility (Factory New)",
            price: 465.00,
            rarity: "Industrial",
            skinName: "Tranquility",
            wear: "Factory New",
            id: "17",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "AK-47",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJegJM6dO4q5KCk_LmDLbUkmJE5fp9i_vG8MKljgDjrkpuZmGiIISRIFU_aQrV81a9kObojMPt6JSYnCRl63Zx5CzZgVXp1oPn8d3r",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "AK-47 | Bloodsport (Minimal Wear)",
            price: 2016.68,
            rarity: "Covert",
            skinName: "Bloodsport",
            wear: "Minimal Wear",
            id: "18",
            isSelected: false,
            isNew: false
        },
        {
            appId: 730,
            gunName: "M4A1-S",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpou-6kejhz2v_Nfz5H_uO1gb-Gw_alIITCmX5d_MR6j_v--YXygECLpxIuNDztII-We1I4aAqE_Fi_lerthMXttc7OnXRmvyhw4Xndlx3kiUkfa-ZuguveFwseJK64Qw",
            isSouvenir: false,
            isStatTrack: true,
            isTradable: true,
            marketHashName: "M4A1-S | Chantico's Fire (Factory New)",
            price: 3520.47,
            rarity: "Covert",
            skinName: "Chantico's Fire",
            wear: "Factory New",
            id: "19",
            isSelected: false,
            isNew: true
        },
        {
            appId: 730,
            gunName: "AK-47",
            img: "-9a81dlWLwJ2UUGcVs_nsVtzdOEdtWwKGZZLQHTxDZ7I56KU0Zwwo4NUX4oFJZEHLbXH5ApeO4YmlhxYQknCRvCo04DEVlxkKgpot7HxfDhjxszJegJM6dO4q5KCk_LmDLbUkmJE5fp9i_vG8MKljgDjrkpuZmGiIISRIFU_aQrV81a9kObojMPt6JSYnCRl63Zx5CzZgVXp1oPn8d3r",
            isSouvenir: false,
            isStatTrack: false,
            isTradable: true,
            marketHashName: "AK-47 | Bloodsport (Minimal Wear)",
            price: 2016.68,
            rarity: "Covert",
            skinName: "Bloodsport",
            wear: "Minimal Wear",
            id: "20",
            isSelected: false,
            isNew: false
        },
    ],
    viewItems: [],
    activeGame: 730,
    searchQuery: "",
    searchResult: [],
    filterMarketHashName: "",
    filterRarity: "",
    filterWear: "",
    sortingPrice: "От дорогих",
    setActiveGame: (gameId) => set({ activeGame: gameId }),
    setItems: (items) => set({ items: items }),
    setViewItems: (items) => set({ viewItems: items }),
    selectItem: (id) => set((state) => {
        const items = state.items.map((item) => {
            if (item.id === id) {
                item.isSelected = !item.isSelected;
            }
            return item;
        });
        return { items };
    }),
    selectAllItems: () => set((state) => {
        const items = state.viewItems.map((item) => {
            item.isSelected = true;
            return item;
        });
        return { viewItems: items };
    }),
    unSelectAllItems: () => set((state) => {
        const items = state.viewItems.map((item) => {
            item.isSelected = false;
            return item;
        });
        return { viewItems: items };
    }),
    setSearchQuery: (searchQuery) => set({ searchQuery: searchQuery }),
    setSearchResult: (searchResult) => set({ searchResult: searchResult }),
    setFilterMarketHashName: (filterMarketHashName) => set({ filterMarketHashName: filterMarketHashName }),
    setFilterRarity: (filterRarity) => set({ filterRarity: filterRarity }),
    setFilterWear: (filterWear) => set({ filterWear: filterWear }),
    setSortingPrice: (sortingPrice) => set({ sortingPrice: sortingPrice }),
}));
